services:
  - type: web
    name: analizador-dgi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 300 --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: AV_KEY
        value: S7P50XU84RPHYGAE
